config/routes.rb
JukebarServer::Application.routes.draw do
  
  resources :bars do
    member do 
      post "register"
      get "next_song"
    end
    
    resources :bar_songs do
      member do
        post "vote"
      end
    end
  end
  
  resources :users
  
  namespace :admin do
    resources :users do
      member do
        post "add_credits"
      end
    end
  end
  

end

app/models/bar.rb
class Bar < ActiveRecord::Base
  has_many :bar_songs
  has_many :actions, :order => "created_at ASC"
  belongs_to :bar_song
  
  def register!
    self.bar_songs.clear
  end
  
  def next_song
    # TODO this is stupidly inefficient #FIXME
    bar_song_votes = self.bar_songs.collect {|bs| [bs.id, bs.votes.active.count] }
    highest_vote_pair = bar_song_votes.sort {|a,b| b[1] <=> a[1]}.first
    if highest_vote_pair[1] == 0 # 0 votes
      {}
    else
      highest_song_id = highest_vote_pair[0]
      BarSong.find(highest_song_id)
    end
  end
  
  def set_status(action_type, *args)
    case action_type
    when /playing/
      self.status = "playing"
      if bar_song = BarSong.find_by_database_ID_and_bar_id(args[0], self.id)
        self.bar_song = bar_song
        self.bar_song.inactivate_votes!
      end
    when /paused/
      self.status = "paused"
      self.bar_song = nil
    end
    save!
  end
  
  def playing!(database_ID)
    set_status(:playing, database_ID)
  end
  
  def paused!
    set_status(:paused)
  end
  
  def to_channel
    "channel-bar-#{self.to_param}"
  end
  
end

app/models/bar_song.rb
class BarSong < ActiveRecord::Base
  belongs_to :bar, :dependent => :destroy
  has_many :votes, :dependent => :destroy
  
  def inactivate_votes!
    votes.active.all.each do |vote|
      vote.active = false
      vote.save!
    end
    self.active_vote_count = 0
    save!
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :name
  has_many :votes
  DEFAULT_CREDITS = 10
  
  before_save :default_values
  
  def can_vote?
    self.credits > 0
  end
  
  def vote(bar_song)
    Rails.logger.info("User #{self.name} voted for #{bar_song.name}")
    Pusher[bar_song.bar.to_channel].trigger("vote", bar_song.attributes)
    self.decrement!(:credits)
    Vote.create(:bar_song => bar_song, :active => true, :user => self)
  end
  
  def add_credits(number)
    self.increment!(:credits, number)
  end
  
  private
  
  def default_values
    self.credits ||= DEFAULT_CREDITS
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :bar_song, :dependent => :destroy
  belongs_to :user, :dependent => :destroy
  
  scope :active, {:conditions => {:active => true}}
  
  after_create :update_bar_song
  
  private
  
  def update_bar_song
    if self.active
      BarSong.update_counters(self.bar_song_id, {:active_vote_count => 1})
    end
    true
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def index
    @users = User.all
  end
  
  def add_credits
    @user = User.find(params[:id])
    @user.add_credits(params[:credits].to_i) if params[:credits]
    redirect_to admin_users_path, :notice => "Added #{params[:credits].to_i} credit(s) to #{@user.name}"
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery
  
  protected
  
  def load_user
    if session[:user_id]
      @user = User.find_by_id(session[:user_id])
    end
    unless @user
      @user = User.create!
      session[:user_id] = @user.id
    end
  end
  
end

app/controllers/bar_songs_controller.rb
class BarSongsController < ApplicationController
  before_filter :load_bar
  before_filter :load_user, :except => [:create]
  respond_to :json, :only => [:index, :vote]
  
  # API method
  def create
    if @bar_song = @bar.bar_songs.find_by_database_ID(params[:bar_song][:database_ID])
      puts "Skipping extant song #{@bar_song.to_json}"
      ; # do nothing
    else
      @song = @bar.bar_songs.create!(params[:bar_song])
    end
    
    head :ok
  end
  
  def index
    @songs = @bar.bar_songs
    respond_with(@songs)
  end
  
  def vote
    @bar_song = BarSong.find(params[:id])
    if @user.can_vote?
      @user.vote(@bar_song)
      render :json => {:user => @user, :song => @bar_song}
    else
      head 402
    end
  end
  
  private
  
  def load_bar
    @bar = Bar.find(params[:bar_id])
  end
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  before_filter :load_user, :only => [:show]
  before_filter :load_bar_by_id
  
  def register
    @bar.register!
    render :json => @bar
  end
  
  def show
    @render_pusher = true
    if @user.name.blank?
      session[:return_bar_id] = @bar.id
      redirect_to(edit_user_path(@user)) 
    end
  end
  
  def next_song
    render :json => @bar.next_song
  end
  
  def update
    if params[:status]
      case params[:status]
      when /playing/
        @bar.playing!(params[:database_ID])
      when /paused|stopped/
        @bar.paused!
      end
    end
    head :ok
  end
  
  private
  
  def load_bar_by_id
    @bar = Bar.find params[:id]
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :load_user
  
  def edit
  end
  
  def update
    @user.attributes = params[:user]
    if @user.save
      redirect_to(:controller => "bars", :action => "show", :id => session[:return_bar_id])
    else
      flash.now[:error] = true
      render :action => "edit"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bar_songs/votes_helper.rb
module BarSongs::VotesHelper
end

app/helpers/bar_songs_helper.rb
module BarSongsHelper
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.haml
%h1 users

%ul
- @users.each do |user|
  %li.user[user]
    .name
      Name
      = user.name
    .credits
      Credits
      = user.credits
    .links
      = link_to "Add #{User::DEFAULT_CREDITS} credits", add_credits_admin_user_path(user, :credits => User::DEFAULT_CREDITS), :method => :post
      = link_to "Add 1 credit", add_credits_admin_user_path(user, :credits => 1), :method => :post
      = link_to "Remove 1 credit", add_credits_admin_user_path(user, :credits => -1), :method => :post

app/views/bar_songs/_show.html.haml
%li{:class => "bar_song", :id => "bar_song_#{bar_song.to_param}"}
  .name
    name:
    %b= bar_song.name
  .artist
    artist:
    %b= bar_song.artist
  .database_ID
    database_ID:
    %b= bar_song.database_ID
  .vote_count
    Votes:
    .actual_vote_count= bar_song.votes.active.count
  .play
    = button_to "Vote now!", {:action => "vote", :id => bar_song.id, :bar_id => @bar.id, :controller => "bar_songs"}, {:remote => true}

app/views/bars/show.html.erb
<div data-role="page" data-theme="b" id="jqm-home"> 
	<div id="jqm-homeheader" data-role="header" data-position="fixed">
	  <h1 id="bar">The JukeBar</h1>
	  <h2>Currently at: <%= @bar.name %></h2>
	  <% if @bar.bar_song %>
  	  <h3>Now playing: <%= @bar.bar_song.name %></h3>
  	<% end %>
    <div class="ui-btn-right">
        Votes Left
        <div class='remaining_votes ui-corner-top ui-corner-bottom' style='text-align: center; border: 1px solid black; padding: 20px; margin-top: 4px;'>
          <%= @user.credits %>
        </div>
    </div>
	  
	  
	  <div data-role="navbar">
      <ul>
        <li><a href="#playlist" data-icon="star" class="ui-btn-active">Playlist</a></li>
        <li><a href="#find_songs" data-icon="search">Find Songs</a></li>
        <li><a href="#my_votes" data-icon="grid">My Votes</a></li>
        <li><a href="#settings" data-icon="gear">Settings</a></li>
      </ul>
  	</div><!-- /navbar -->
	</div> 
	
	<div data-role="content"> 
		<ul data-role="listview" data-split-icon="gear" data-split-theme="d" id="bar_songs"> 
			<li data-role="list-divider">Songs</li>
			<% bar_songs = @bar.bar_songs.sort_by{|bar_song| bar_song.votes.active.count }.reverse %>
			<% bar_songs.each do |bar_song| %>
			  <li class='bar_song' id="bar_song_<%= bar_song.to_param %>">
		      <h3><%= bar_song.name %></h3>
		      <p>
  		      <%= bar_song.artist %>
		      </p>
		      <span class="ui-li-count"><%= bar_song.votes.active.count %></span>
		      <p class='ui-li-aside'>
		        <a href='#' data-role='button' data-theme="b" class='vote' data-song-id="<%= bar_song.id %>">Vote!</a>
		      </p>
		    </li>
			<% end %>
		</ul> 
	</div>
</div>

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title Jukebar server Admin
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = javascript_include_tag "underscore.js"
    = javascript_include_tag "jquery-growl"
    = javascript_include_tag "jukebar"
    = csrf_meta_tag
    = render :partial => "/shared/pusher" if @render_pusher
  %body#admin
    - if flash[:notice]
      #notice=flash[:notice]
    = yield

app/views/layouts/application.html.erb
<!DOCTYPE html> 
<html> 
<head> 
  <meta charset="utf-8"> 
  <meta name="viewport" content="width=device-width, minimum-scale=1, maximum-scale=1"> 
  <title>jQuery Mobile: Demos and Documentation</title> 
  <link rel="stylesheet"  href="http://code.jquery.com/mobile/1.0a4.1/jquery.mobile-1.0a4.1.min.css" /> 
  <script type="text/javascript" src="http://code.jquery.com/jquery-1.5.min.js"></script> 
  <script type="text/javascript" src="http://code.jquery.com/mobile/1.0a4.1/jquery.mobile-1.0a4.1.min.js"></script> 
  <%= javascript_include_tag "/javascripts/quicksilver.js" %>
  <%= javascript_include_tag "/javascripts/jukebarcoffee.js" %>
  <%= javascript_include_tag "http://js.pusherapp.com/1.7/pusher.min.js" %>
  
</head> 
<body> 
  <%= yield %>
</body>
</html>

app/views/users/edit.haml
%div{"data-role" => "page"}
  - if flash[:error]
    = error_messages_for @user
  = form_for @user do |f|
    %div{"data-role" => "fieldcontain"}
      %label{:for => "name"} Name
      = f.text_field :name